name: sRGB-TIR
channels:
  - defaults
  - pytorch
  - conda-forge
  - anaconda
  - pypi
dependencies:
  - python=3.12.8
  - pip=24.2
  - setuptools=75.1.0
  - wheel=0.44.0
  - numpy=2.2.1
  - scipy=1.14.1
  - matplotlib=3.10.0
  - scikit-image=0.25.0
  - pillow=11.0.0
  - opencv-python=4.10.0.84
  - imageio=2.36.1
  - networkx=3.4.2
  - sympy=1.13.1
  - protobuf=5.29.2
  - pyyaml=6.0.2
  - filelock=3.13.1
  - tensorboardx=2.6.2.2
  - torch=2.5.1+cu124
  - torchvision=0.20.1+cu124
  - torchaudio=2.5.1+cu124
  - torchfile=0.1.0
